name: backend-ci

on:
  push:
    paths:
      comdel-backend/**
    branches:
      - main
  pull_request:
    paths:
      comdel-backend/**
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    name: build-dependency
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      
      - name: Go Module Cache
        id: mod-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{hashFiles('comdel-backend/go.sum')}}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: build project
        if: steps.mod-cache.outputs.cache_hit != 'true'
        run: |
          cd comdel-backend
          go mod tidy
          go build ./...
  
  test:
    name: test-dependency
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Go Module Cache
        id: mod-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{hashFiles('comdel-backend/go.sum')}}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: test code
        run: |
          cd comdel-backend/internal/services
          go test -v
